config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  resources :points, only: [:index] do
    collection do
      get :add_poi
      get :add_ror
      get :add_statement
      get :add_mod_speech
      get :add_mod_topic
      get :add_reso_speech
      get :add_amends
      get :add_amends_speech
      get :add_unmod
      get :add_activism
      get :add_lobby
      get :add_behaviour
      get :add_diplomacy
      get :add_fps
      get :add_fp_violation
      get :add_sponsor
    end
  end
  root to: 'pages#index'
end

app/models/delegate.rb
class Delegate < ActiveRecord::Base
  default_scope { order('country') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  def add_poi
    mark = params[:mark].to_i
    delegate_id = params[:delegate_id]
    unless mark < 0
      @delegate = Delegate.find(delegate_id)

      @delegate.poi_total = @delegate.poi_total + mark
      @delegate.poi_count = @delegate.poi_count + 1
      @delegate.poi_average = @delegate.poi_total / @delegate.poi_count
      @delegate.save
    end
  end

  def add_ror
    mark = params[:mark].to_i
    delegate_id = params[:delegate_id]
    unless mark < 0
      @delegate = Delegate.find(delegate_id)

      @delegate.ror_total = @delegate.ror_total + mark
      @delegate.ror_count = @delegate.ror_count + 1
      @delegate.ror_average = @delegate.ror_total / @delegate.ror_count
      @delegate.save
    end
  end
  def add_statement
    mark = params[:mark].to_i
    delegate_id = params[:delegate_id]
    unless mark < 0
      @delegate = Delegate.find(delegate_id)

      @delegate.statement_total = @delegate.statement_total + mark
      @delegate.statement_count = @delegate.statement_count + 1
      @delegate.statement_average = @delegate.statement_total / @delegate.statement_count
      @delegate.save
    end
  end
  def add_mod_speech
    mark = params[:mark].to_i
    delegate_id = params[:delegate_id]
    unless mark < 0
      @delegate = Delegate.find(delegate_id)

      @delegate.mod_speech_total = @delegate.mod_speech_total + mark
      @delegate.mod_speech_count = @delegate.mod_speech_count + 1
      @delegate.mod_speech_average = @delegate.mod_speech_total / @delegate.mod_speech_count
      @delegate.save
    end
  end
  def add_mod_topic
    mark = params[:mark].to_i
    delegate_id = params[:delegate_id]
    unless mark < 0
      @delegate = Delegate.find(delegate_id)

      @delegate.mod_topic_total = @delegate.mod_topic_total + mark
      @delegate.mod_topic_count = @delegate.mod_topic_count + 1
      @delegate.mod_topic_average = @delegate.mod_topic_total / @delegate.mod_topic_count
      @delegate.save
    end
  end
  def add_reso_speech
    mark = params[:mark].to_i
    delegate_id = params[:delegate_id]
    unless mark < 0
      @delegate = Delegate.find(delegate_id)

      @delegate.reso_speech_total = @delegate.reso_speech_total + mark
      @delegate.reso_speech_count = @delegate.reso_speech_count + 1
      @delegate.reso_speech_average = @delegate.reso_speech_total / @delegate.reso_speech_count
      @delegate.save
    end
  end
  def add_amends
    mark = params[:mark].to_i
    delegate_id = params[:delegate_id]
    unless mark < 0
      @delegate = Delegate.find(delegate_id)

      @delegate.amends_total = @delegate.amends_total + mark
      @delegate.amends_count = @delegate.amends_count + 1
      @delegate.amends_average = @delegate.amends_total / @delegate.amends_count
      @delegate.save
    end
  end
  def add_amends_speech
    mark = params[:mark].to_i
    delegate_id = params[:delegate_id]
    unless mark < 0
      @delegate = Delegate.find(delegate_id)

      @delegate.amends_speech_total = @delegate.amends_speech_total + mark
      @delegate.amends_speech_count = @delegate.amends_speech_count + 1
      @delegate.amends_speech_average = @delegate.amends_speech_total / @delegate.amends_speech_count
      @delegate.save
    end
  end
  def add_unmod
    mark = params[:mark].to_i
    delegate_id = params[:delegate_id]
    unless mark < 0
      @delegate = Delegate.find(delegate_id)
      @delegate.unmod = mark
      @delegate.save
    end
  end
  def add_activism
    mark = params[:mark].to_i
    delegate_id = params[:delegate_id]
    unless mark < 0
      @delegate = Delegate.find(delegate_id)
      @delegate.activism = mark
      @delegate.save
    end
  end
  def add_lobby
    mark = params[:mark].to_i
    delegate_id = params[:delegate_id]
    unless mark < 0
      @delegate = Delegate.find(delegate_id)
      @delegate.lobby = mark
      @delegate.save
    end
  end
  def add_behaviour
    mark = params[:mark].to_i
    delegate_id = params[:delegate_id]
    unless mark < 0
      @delegate = Delegate.find(delegate_id)
      @delegate.behaviour = mark
      @delegate.save
    end
  end
  def add_diplomacy
    mark = params[:mark].to_i
    delegate_id = params[:delegate_id]
    unless mark < 0
      @delegate = Delegate.find(delegate_id)
      @delegate.diplomacy = mark
      @delegate.save
    end
  end
  def add_fps
    mark = params[:mark].to_i
    delegate_id = params[:delegate_id]
    unless mark < 0
      @delegate = Delegate.find(delegate_id)
      @delegate.fps = mark
      @delegate.save
    end
  end
  def add_fp_violation
    mark = params[:mark].to_i
    delegate_id = params[:delegate_id]
    unless mark < 0
      @delegate = Delegate.find(delegate_id)
      @delegate.fp_violation = mark
      @delegate.save
    end
  end
  def add_sponsor
    mark = params[:mark]
    delegate_id = params[:delegate_id]

      @delegate = Delegate.find(delegate_id)
      @delegate.sponsor = mark
      @delegate.save

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_navigation(title, controller)
    'active' if title == controller            
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/points_helper.rb
module PointsHelper
  def countries
    Delegate.all
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MunPoint
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.blue.accent-2.darken-3
      .nav-wrapper
        %a.brand-logo.center{ href: root_path } SLMUN Point System
        %ul#nav-mobile.right.hide-on-med-and-down
          %li{class: active_navigation('points', params[:controller])}
            %a{href: points_path} Points System


    .container
      .spacer
      = yield
      = debug(params) if Rails.env.development?

app/views/pages/index.html.haml
.row
  .col.m6.offset-m3
    .card.blue.lighten-1.hoverable
      .card-content.white-text
        %span.card-title Welcome
        %p
          Welcome to the SLMUN Conference System.
    

app/views/points/add_amends.js.erb
$('#amends').val("");
Materialize.toast('Amendment Added!', 4000);

app/views/points/add_amends_speech.js.erb
$('#amends-speech').val("");
Materialize.toast('Amendment Speech Added!', 4000);

app/views/points/add_behaviour.js.erb
$('#behaviour').val("");
Materialize.toast('Behaviour Score Updated!', 4000);

app/views/points/add_diplomacy.js.erb
$('#diplomacy').val("");
Materialize.toast('Diplomacy Score Updated!', 4000);

app/views/points/add_fps.js.erb
$('#fps').val("");
Materialize.toast('FPS Score Updated!', 4000);

app/views/points/add_lobby.js.erb
$('#lobby').val("");
Materialize.toast('Lobby Score Updated!', 4000);

app/views/points/add_mod_speech.js.erb
$('#mod-speech').val("");
Materialize.toast('Moderated Speech Added!', 4000);

app/views/points/add_mod_topic.js.erb
$('#mod-topic').val("");
Materialize.toast('Moderated Topic Added!', 4000);

app/views/points/add_poi.js.erb
$('#poi').val("");
Materialize.toast('POI Added!', 4000);

app/views/points/add_reso_speech.js.erb
$('#reso-speech').val("");
Materialize.toast('Resolution Speech Added!', 4000);

app/views/points/add_sponsor.js.erb
$('#sponsor').val("");
Materialize.toast('Sponsor Status Updated!', 4000);

app/views/points/add_statement.js.erb
$('#statement').val("");
Materialize.toast('Statement Added!', 4000);

app/views/points/add_unmod.js.erb
$('#unmod').val("");
Materialize.toast('Unmod Score Updated!', 4000);

app/views/points/index.html.haml
.row
  .col.s12
    %label Delegate Country
    %select.browser-default#country
      - countries.each do |country|
        %option{:value => country.id}
          = country.country

    .card.blue.lighten-1
      .card-content.black-text
        %span.card-title Points
        .spacer-1
        .row
          .col.s3
            .input-field
              %input.validate#poi{:type => "number"}
                %label{} POI
            %a.waves-effect.waves-light.btn.indigo.darken-1.btn-poi Add POI
          .col.s3
            .input-field
              %input.validate#ror{:type => "number"}
                %label{} ROR
            %a.waves-effect.waves-light.btn.indigo.darken-1.btn-ror Add ROR
          .col.s3
            .input-field
              %input.validate#statement{:type => "number"}
                %label{} Statement
            %a.waves-effect.waves-light.btn.indigo.darken-1.btn-statement Add Statement
          .col.s3
            .input-field
              %input.validate#mod-speech{:type => "number"}
                %label{} Moderated Speech
            %a.waves-effect.waves-light.btn.indigo.darken-1.btn-mod-speech Add Moderated Speech
        .row
          .col.s3
            .input-field
              %input.validate#mod-topic{:type => "number"}
                %label{} Moderated Topic
            %a.waves-effect.waves-light.btn.indigo.darken-1.btn-mod-topic Add Moderated Topic
          .col.s3
            .input-field
              %input.validate#reso-speech{:type => "number"}
                %label{} Resolution Speech
            %a.waves-effect.waves-light.btn.indigo.darken-1.btn-reso-speech Add Resolution Speech
          .col.s3
            .input-field
              %input.validate#amends{:type => "number"}
                %label{} Amendment
            %a.waves-effect.waves-light.btn.indigo.darken-1.btn-amends Add Amendment
          .col.s3
            .input-field
              %input.validate#amends-speech{:type => "number"}
                %label{} Amend Speech
            %a.waves-effect.waves-light.btn.indigo.darken-1.btn-amends-speech Add Amendment Speech
        .row
          .col.s2
            .input-field
              %input.validate#unmod{:type => "number"}
                %label{} Unmod
            %a.waves-effect.waves-light.btn.indigo.darken-1.btn-unmod Update Unmod
          .col.s2
            .input-field
              %input.validate#activism{:type => "number"}
                %label{} Activism
            %a.waves-effect.waves-light.btn.indigo.darken-1.btn-activism Update Activism
          .col.s2
            .input-field
              %input.validate#lobby{:type => "number"}
                %label{} Lobby
            %a.waves-effect.waves-light.btn.indigo.darken-1.btn-lobby Update Lobby
          .col.s2
            .input-field
              %input.validate#behaviour{:type => "number"}
                %label{} Behaviour
            %a.waves-effect.waves-light.btn.indigo.darken-1.btn-behaviour Update Behaviour
          .col.s2
            .input-field
              %input.validate#diplomacy{:type => "number"}
                %label{} Diplomacy
            %a.waves-effect.waves-light.btn.indigo.darken-1.btn-diplomacy Update Diplomacy
          .col.s2
            .input-field
              %input.validate#fps{:type => "number"}
                %label{} FPS
            %a.waves-effect.waves-light.btn.indigo.darken-1.btn-fps Update FPS
        .row
          .col.s2.offset-s4
            .input-field
              %input.validate#fp-violation{:type => "number"}
                %label{} FP Violation
            %a.waves-effect.waves-light.btn.indigo.darken-1.btn-fp-violation Add FP Violation
          .col.s2
            .input-field
              %select.browser-default#sponsor
                %option{:disabled => "", :selected => "", :value => ""} Sponsor
                %option{:value => "true"} Yes
                %option{:value => "false"} No



:javascript
  $(document).ready(function() {

    $('.btn-poi').on('click', function() {
      $.ajax({
         url: "#{add_poi_points_path}",
         data: {
             mark: $('#poi').val(),
             delegate_id: $('#country').val()
         },
         dataType: "script"
      });
    });
    $('.btn-ror').on('click', function() {
      $.ajax({
         url: "#{add_ror_points_path}",
         data: {
             mark: $('#ror').val(),
             delegate_id: $('#country').val()
         },
         dataType: "script"
      });
    });
    $('.btn-statement').on('click', function() {
      $.ajax({
         url: "#{add_statement_points_path}",
         data: {
             mark: $('#statement').val(),
             delegate_id: $('#country').val()
         },
         dataType: "script"
      });
    });
    $('.btn-mod-speech').on('click', function() {
      $.ajax({
         url: "#{add_mod_speech_points_path}",
         data: {
             mark: $('#mod-speech').val(),
             delegate_id: $('#country').val()
         },
         dataType: "script"
      });
    });
    $('.btn-mod-topic').on('click', function() {
      $.ajax({
         url: "#{add_mod_topic_points_path}",
         data: {
             mark: $('#mod-topic').val(),
             delegate_id: $('#country').val()
         },
         dataType: "script"
      });
    });
    $('.btn-reso-speech').on('click', function() {
      $.ajax({
         url: "#{add_reso_speech_points_path}",
         data: {
             mark: $('#reso-speech').val(),
             delegate_id: $('#country').val()
         },
         dataType: "script"
      });
    });
    $('.btn-amends').on('click', function() {
      $.ajax({
         url: "#{add_amends_points_path}",
         data: {
             mark: $('#amends').val(),
             delegate_id: $('#country').val()
         },
         dataType: "script"
      });
    });
    $('.btn-amends-speech').on('click', function() {
      $.ajax({
         url: "#{add_amends_speech_points_path}",
         data: {
             mark: $('#amends-speech').val(),
             delegate_id: $('#country').val()
         },
         dataType: "script"
      });
    });
    $('.btn-unmod').on('click', function() {
      $.ajax({
         url: "#{add_unmod_points_path}",
         data: {
             mark: $('#unmod').val(),
             delegate_id: $('#country').val()
         },
         dataType: "script"
      });
    });
    $('.btn-activism').on('click', function() {
      $.ajax({
         url: "#{add_activism_points_path}",
         data: {
             mark: $('#activism').val(),
             delegate_id: $('#country').val()
         },
         dataType: "script"
      });
    });
    $('.btn-lobby').on('click', function() {
      $.ajax({
         url: "#{add_lobby_points_path}",
         data: {
             mark: $('#lobby').val(),
             delegate_id: $('#country').val()
         },
         dataType: "script"
      });
    });
    $('.btn-behaviour').on('click', function() {
      $.ajax({
         url: "#{add_behaviour_points_path}",
         data: {
             mark: $('#behaviour').val(),
             delegate_id: $('#country').val()
         },
         dataType: "script"
      });
    });
    $('.btn-diplomacy').on('click', function() {
      $.ajax({
         url: "#{add_diplomacy_points_path}",
         data: {
             mark: $('#diplomacy').val(),
             delegate_id: $('#country').val()
         },
         dataType: "script"
      });
    });
    $('.btn-fps').on('click', function() {
      $.ajax({
         url: "#{add_fps_points_path}",
         data: {
             mark: $('#fps').val(),
             delegate_id: $('#country').val()
         },
         dataType: "script"
      });
    });
    $('.btn-fp-violation').on('click', function() {
      $.ajax({
         url: "#{add_fp_violation_points_path}",
         data: {
             mark: $('#fp-violation').val(),
             delegate_id: $('#country').val()
         },
         dataType: "script"
      });
    });
    $('#sponsor').on('change', function() {
      $.ajax({
         url: "#{add_sponsor_points_path}",
         data: {
             mark: $('#sponsor').val(),
             delegate_id: $('#country').val()
         },
         dataType: "script"
      });
    });
  });